version: '3.0'

services:
  discovery-service:
    image: jmprathab/myhome-service:${TAG:-latest}
    build:
      dockerfile: Dockerfile
    container_name: "myhome-service"
    networks:
      - myhome
    expose:
      - "80"
    ports:
      - "80:80"

networks:
  myhome:
