version: '3.0'

services:
  discovery-service:
    image: jmprathab/myhome-discovery-service:${TAG:-latest}
    build:
      context: discovery-service
      dockerfile: Dockerfile
    container_name: "myhome-discovery-service"
    networks:
      - myhome
    expose:
      - "8010"
    ports:
      - "8010:8010"

  api-gateway-service:
    image: jmprathab/myhome-api-gateway-service:${TAG:-latest}
    build:
      context: api-gateway-service
      dockerfile: Dockerfile
    container_name: "myhome-api-gateway-service"
    networks:
      - myhome
    expose:
      - "8011"
    ports:
      - "8011:8011"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://myhome-discovery-service:8010/eureka
    depends_on:
      - discovery-service

  user-service:
    image: jmprathab/myhome-user-service:${TAG:-latest}
    build:
      context: user-service
      dockerfile: Dockerfile
    container_name: "myhome-user-service"
    networks:
      - myhome
    environment:
      - eureka.client.serviceUrl.defaultZone=http://myhome-discovery-service:8010/eureka
      - gateway.ip=myhome-api-gateway-service
    depends_on:
      - api-gateway-service
      - discovery-service

  community-service:
    image: jmprathab/myhome-community-service:${TAG:-latest}
    build:
      context: community-service
      dockerfile: Dockerfile
    container_name: "myhome-community-service"
    networks:
      - myhome
    environment:
      - eureka.client.serviceUrl.defaultZone=http://myhome-discovery-service:8010/eureka
      - gateway.ip=myhome-api-gateway-service
    depends_on:
      - api-gateway-service
      - discovery-service

networks:
  myhome:
