openapi: 3.0.2
servers:
  - url: /v3
info:
  description: This is a OpenApi specification for MyHome backend service.
  version: 2.0.0
  title: Swagger MyHome - OpenAPI 3.0
tags:
  - name: Users
paths:
  /users:
    post:
      tags:
        - Users
      description: "Create a new user"
      operationId: signUp
      requestBody:
        description: CreateUserRequest aggregate fields
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: "if user created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        '409':
          description: "if user already exists"

components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
          maxLength: 80
    CreateUserResponse:
      type: object
      properties:
        userId:
          type: string
        name:
          type: string
        email:
          type: string