###############################################################################
# Server properties
###############################################################################
server.port: 8010
spring.application.name: "discovery-service"

###############################################################################
# Eureka Discovery
###############################################################################
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://localhost:8010/eureka"
